### PR TITLE
Set up Stub state machine

### PR DESCRIPTION
**Pull request by baskaufs**
In the process of working on Issue #6 I've mostly gotten the state machines set up, although some of the pieces may need to be moved around.  You can see the diagrams [here](https://github.com/HeardLibrary/cloud-tvnews/blob/stateMachine/stateMachines/README.md).

### CODE REVIEW

**Comment by jimdur8n** [comment]
@baskaufs the processingSnapstreamData will need the attached logic. Should we write this into the statemachine?
processingSnapstreamData

**Comment by baskaufs** [comment]
I was thinking about the initial processing step yesterday and I think we need a lambda that sorts out the bucket drops.  I looked at the setup for the CloudTrail monitoring and although you can specify particular buckets, you can't specify a filename pattern to be matched as you can when a lambda gets triggered directly by an S3 load event.  Whether that gets done in a separate lambda from one that renames the file probably isn't important, but it will need to be written into the logic.  

As far as your question goes, although there is a certain amount of logic that can be done directly at the state machine level, I don't see any big advantage over just putting the logic into the Python lambda that the state machine runs.  I also don't think it's that important whether there are several small lambdas that run sequentially or one bigger lambda that does the whole thing.  Breaking it into smaller lambdas would make it easier to monitor points of failure, but also would require more management of the data that gets passed from one state machine to another.

**Comment by jimdur8n** [comment]
Okay, heres how I think processingSnapStream should look:

Lambda 0 (L0): Is this bucket drop important? yes/no
Lambda 1 (L1): If L0 = yes, f(x) and g(y). returns yes/no for unique
Lambda 2 (L2): Runs if L1 = no, handles h(z), j(z). returns yes/no for timeOverlap
Lambda 3 (L3): Runs if L1 = yes, or L2 = no, Renames x, using all the variables above. then sorts into buckets.
Lambda 4 (L4): This only runs if L2 = yes, which means the file is a duplicate and can be removed.

Should I put this into a statemachine?

**Comment by baskaufs** [comment]
This looks great!  Breaking it into small lambdas would make tracking easier.  The logical flow can be captured in the state machines with the actual code being built later.  Cool!

**Comment by jimdur8n** [comment]
I'm going to close this pull request, I think we're ready.

**Review by jimdur8n — COMMENTED** [review]
I think this looks good as an initial starting point.

**Comment by baskaufs** [comment]
Since this didn't get merged, I'll reopen it and try to make the several state machines that @jimdur8n described above before actually doing the merge.

**Pull request merged**
